<a href="https://colab.research.google.com/github/ErnestoAvedillo/42Barcelona/blob/main/AAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

**### Primera parte**

Cálculo del coste de las demandas internas.

n = nḿero de referencias.

REF = diccionario con las referencias de la empresa (TODAS , las de compra , internas  y de producto acabado.)

DC = Demanda de cliente

BOM = es una tabla de n x n con el BOM de los producto (Todos)

In [166]:
#numero de referencias
n = 8
#BILL OF MATERIALS
BOM = np.zeros((n,n))
#Diccionario de referencias
#REF = {"1":0,"2":1,"3":2,"4":3,"5":4,"6":5,"7":6,"8":7}
REF = {}
for i in range(0,n):
  num = str(i + 1)
  REF[num] = i
#Demandas de cliente
DC = np.zeros((n,1))

Simulacion de un BOM con dos productos diferentes

In [167]:
#BOM for product 1
BOM[REF["5"],REF["3"]] = 0.5
BOM[REF["5"],REF["7"]] = 2
BOM[REF["7"],REF["1"]] = 1

#BOM for product 2
BOM[REF["6"],REF["3"]] = 0.75
BOM[REF["6"],REF["4"]] = 1
BOM[REF["6"],REF["8"]] = 1
BOM[REF["8"],REF["2"]] = 1

print(BOM)
print(REF)

[[0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.5  0.   0.   0.   2.   0.  ]
 [0.   0.   0.75 1.   0.   0.   0.   1.  ]
 [1.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   1.   0.   0.   0.   0.   0.   0.  ]]
{'1': 0, '2': 1, '3': 2, '4': 3, '5': 4, '6': 5, '7': 6, '8': 7}


In [168]:
#DEMANDAS DE CLIENTE
DC[REF["5"]]=7
DC[REF["6"]]=10
print (DC)

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 7.]
 [10.]
 [ 0.]
 [ 0.]]


Listado de Maquinaria

m = número de máquinas

DICMAQ = Diccionario de maquinaria (m x 1)

BOMMAQ = Listado de maquinaria por referencia (m x n)

In [190]:
m = 3
BOMMAQ = np.zeros((m,n))
DICMAQ = {"Compras":0,"mecanizado":1,"inyeccion":2}
#BOMMAQ[DICMAQ["Compras"],REF["1"]] = 1
#BOMMAQ[DICMAQ["Compras"],REF["2"]] = 1
#BOMMAQ[DICMAQ["Compras"],REF["3"]] = 1
#BOMMAQ[DICMAQ["Compras"],REF["4"]] = 1
BOMMAQ[DICMAQ["inyeccion"],REF["5"]] = 1
BOMMAQ[DICMAQ["inyeccion"],REF["6"]] = 1
BOMMAQ[DICMAQ["mecanizado"],REF["7"]] = 1
BOMMAQ[DICMAQ["mecanizado"],REF["8"]] = 1
print(BOMMAQ)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1. 0. 0.]]


In [191]:
#Voy incremetnando la matriz de demandas a medida que aumenta el nicel de fabricación
index = DC.shape[1]
DINT = np.dot(BOM.T, DC[:,index - 1])
DINT = np.expand_dims(DINT, axis = 1)
while(np.sum(DINT) != 0):
  DC = np.concatenate((DC, DINT), axis = 1)
  DINT = np.dot(BOM.T, DC[:,DC.shape[1] - 1])
  DINT = np.expand_dims(DINT, axis = 1)
print(DC)

[[ 0.  0. 14.]
 [ 0.  0. 10.]
 [ 0. 11.  0.]
 [ 0. 10.  0.]
 [ 7.  0.  0.]
 [10.  0.  0.]
 [ 0. 14.  0.]
 [ 0. 10.  0.]]


In [192]:
#DINT se corresponde a las demandas internas
for i in list(REF):
  print("Referencia " ,i, " Demanda CLIENTE --> ", DC[REF[i],0])
for j in range(1, DC.shape[1] - 1):
  for i in list(REF):
    print("Referencia " ,i, " Demanda interna nivel ", j, " --> ", DC[REF[i],j])
for i in list(REF):
  print("Referencia " ,i, " Demanda interna (compras) nivel 0 --> ", DC[REF[i],DC.shape[1] - 1])


Referencia  1  Demanda CLIENTE -->  0.0
Referencia  2  Demanda CLIENTE -->  0.0
Referencia  3  Demanda CLIENTE -->  0.0
Referencia  4  Demanda CLIENTE -->  0.0
Referencia  5  Demanda CLIENTE -->  7.0
Referencia  6  Demanda CLIENTE -->  10.0
Referencia  7  Demanda CLIENTE -->  0.0
Referencia  8  Demanda CLIENTE -->  0.0
Referencia  1  Demanda interna nivel  1  -->  0.0
Referencia  2  Demanda interna nivel  1  -->  0.0
Referencia  3  Demanda interna nivel  1  -->  11.0
Referencia  4  Demanda interna nivel  1  -->  10.0
Referencia  5  Demanda interna nivel  1  -->  0.0
Referencia  6  Demanda interna nivel  1  -->  0.0
Referencia  7  Demanda interna nivel  1  -->  14.0
Referencia  8  Demanda interna nivel  1  -->  10.0
Referencia  1  Demanda interna (compras) nivel 0 -->  14.0
Referencia  2  Demanda interna (compras) nivel 0 -->  10.0
Referencia  3  Demanda interna (compras) nivel 0 -->  0.0
Referencia  4  Demanda interna (compras) nivel 0 -->  0.0
Referencia  5  Demanda interna (compras) 

Ahora vamos a buscar el minimo común múltiplo entre las demandas y las piezas por caja
Posteriormente calcularemos el tiempo de trabajo necesario para cada un o de los niveles de producción.

T =  Tiempos de ciclo (n x 1) (Dato a recibir de cliente)

BOX = Piezas por caja (n x 1)

In [193]:
#Tiempo de ciclo estimado en los procesos
T= np.ones((n, 1))
T[REF["5"]] = 120
T[REF["6"]] = 135
T[REF["7"]] = 90
T[REF["8"]] = 80
print(T)

[[  1.]
 [  1.]
 [  1.]
 [  1.]
 [120.]
 [135.]
 [ 90.]
 [ 80.]]


In [194]:
#Estimo las piezs por caja de cada componente
import random
BOX = np.ones((n,1))
for i in range(n):
  BOX[i - 1] = random.randrange(5,10)
print (BOX)

[[8.]
 [7.]
 [7.]
 [5.]
 [6.]
 [9.]
 [6.]
 [9.]]


In [195]:
#Busco en número de cajas necesario para la produccion
mask = np.mod(DC, BOX) > 0
ones_array = np.zeros_like(np.mod(DC, BOX))
ones_array [mask] = 1
DCBOX = np.floor_divide(DC, BOX) +  ones_array
print (DCBOX)


[[0. 0. 2.]
 [0. 0. 2.]
 [0. 2. 0.]
 [0. 2. 0.]
 [2. 0. 0.]
 [2. 0. 0.]
 [0. 3. 0.]
 [0. 2. 0.]]


In [196]:
DCHORAS = np.divide(DCBOX,T)
print(DCHORAS)

[[0.         0.         2.        ]
 [0.         0.         2.        ]
 [0.         2.         0.        ]
 [0.         2.         0.        ]
 [0.01666667 0.         0.        ]
 [0.01481481 0.         0.        ]
 [0.         0.03333333 0.        ]
 [0.         0.025      0.        ]]



MAQ = is a vector of ONES where there is an operation


In [198]:
MAQ = np.multiply(np.expand_dims(DCHORAS.sum(axis = 1), axis = 1), BOMMAQ.T)
print (MAQ)

[[0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.01666667]
 [0.         0.         0.01481481]
 [0.         0.03333333 0.        ]
 [0.         0.025      0.        ]]


Ahora nos centraremso en el cálculo de la mano de obra

MAQREF = Vector Maquinas (n x 1)

MOM = Coste de la mano de obra Turno de mañana

MOT = Coste de la mano de obra Turno de tarde

MON = Coste de la mano de obra Turno de noche

MHORARIA = MATRIZ Horaria (n x 24)

NOP =  Número de operarios (n x 1) (Dato a recibir de cliente)

CMOTHORARIO = Coste de mano de obra total (nx24) resultado de MOTURNOS * MOP *T / 3600

In [206]:
MAQREF = np.zeros((n,1))
mask = BOMMAQ.sum(axis = 0) > 0
MAQREF[mask] = 1
print(MAQREF)
MHORARIA = np.ones((n,24))
MOTURNOS = np.multiply(MHORARIA, MAQREF)
print(MOTURNOS)

[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [207]:
MOM = 12
MOT = 14
MON = 18
MOTURNOS [:,0:6] *=  MON
MOTURNOS [:,6:14] *=  MOM
MOTURNOS [:,14:22] *=  MOT
MOTURNOS [:,22:24] *=  MON
print(MOTURNOS)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.]
 [18. 18. 18. 18. 18. 18. 12. 12. 12. 12. 12. 12. 12. 12. 14. 14. 14. 14.
  14. 14. 14. 14. 18. 18.]
 [18. 18. 18. 18. 18. 18. 12. 12. 12. 12. 12. 12. 12. 12. 14. 14. 14. 14.
  14. 14. 14. 14. 18. 18.]
 [18. 18. 18. 18. 18. 18. 12. 12. 12. 12. 12. 12. 12. 12. 14. 14. 14. 14.
  14. 14. 14. 14. 18. 18.]
 [18. 18. 18. 18. 18. 18. 12. 12. 12. 12. 12. 12. 12. 12. 14. 14. 14. 14.
  14. 14. 14. 14. 18. 18.]]


In [209]:
#Numero de operarios estimado en los procesos
NOP= np.copy(MAQREF)
NOP[REF["5"]] = 2
NOP[REF["6"]] = 3
NOP[REF["7"]] = 1
NOP[REF["8"]] = 1
print(NOP)

[[0.]
 [0.]
 [0.]
 [0.]
 [2.]
 [3.]
 [1.]
 [1.]]


In [222]:
CMOTHORARIO  =np.multiply(MOTURNOS, np.multiply(T,NOP)) / 3600
print(CMOTHORARIO)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [1.


Ahora nos centraremso en el cálculo de la mano de obra

MAQ = Vector Maquinas (n x 1)

CMF = Coste máquina fijo (n x 24)

CPOT = Tabla de coste de potencias (n x 24)

POT = Potencia de Maquinaria (n x 1) KWH

CELECM = Coste potencia turno mañana

CELECT = coste potencia turno tarde

CELECN = Coste potencia turno Noche

CMVTURNOS = Coste maquina variable (n x 24))

T =  Tiempos de ciclo (n x 1) (Definidos anteriormente)

CMQVTHORARIO = Coste de maquina total (nx24) resultado de CMVTURNOS * POT *T / 3600

CMTOT = (CMF + CMQVTHORARIO) * T / 3600

In [223]:
from genericpath import commonprefix
#Coste maquina definido por cliente CMF
cmfijo = 5  #5 es un valor estimado
CMF = np.ones((n,24))
CMF = np.multiply(CMF, MAQREF)
CMF = CMF * cmfijo
print (CMF)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [224]:
#Numero de operarios estimado en los procesos
CPOT= np.copy(MAQREF)
CPOT[REF["5"]] = 50
CPOT[REF["6"]] = 60
CPOT[REF["7"]] = 120
CPOT[REF["8"]] = 12
print(CPOT)

[[  0.]
 [  0.]
 [  0.]
 [  0.]
 [ 50.]
 [ 60.]
 [120.]
 [ 12.]]


In [225]:
CMTURNOS = np.ones((n,24))
CMTURNOS = np.multiply(CMTURNOS, MAQREF)
print(CMTURNOS)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [226]:

CELECM = 0.12
CELECT = 0.14
CELECN = 0.16
CMTURNOS [:,0:6] *=  CELECN
CMTURNOS [:,6:14] *=  CELECM
CMTURNOS [:,14:22] *=  CELECT
CMTURNOS [:,22:24] *=  CELECN
print(CMTURNOS)

[[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.16 0.16 0.16 0.16 0.16 0.16 0.12 0.12 0.12 0.12 0.12 0.12 0.12 0.12
  0.14 0.14 0.14 0.14 0.14 0.14 0.14 0.14 0.16 0.16]
 [0.16 0.16 0.16 0.16 0.16 0.16 0.12 0.12 0.12 0.12 0.12 0.12 0.12 0.12
  0.14 0.14 0.14 0.14 0.14 0.14 0.14 0.14 0.16 0.16]
 [0.16 0.16 0.16 0.16 0.16 0.16 0.12 0.12 0.12 0.12 0.12 0.12 0.12 0.12
  0.14 0.14 0.14 0.14 0.14 0.14 0.14 0.14 0.16 0.16]
 [0.16 0.16 0.16 0.16 0.16 0.16 0.12 0.12 0.12 0.12 0.12 0.12 0.12 0.12
  0.14 0.14 0.14 0.14 0.14 0.14 0.14 0.14 0.16 0.16]]


In [227]:
CMQVTHORARIO  = np.multiply(CMTURNOS , CPOT)
print(CMQVTHORARIO)

[[ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 8.    8.    8.    8.    8.    8.    6.    6.    6.    6.    6.    6.
   6.    6.    7.    7.    7.    7.    7.    7.    7.    7.    8.    8.  ]
 [ 9.6   9.6   9.6   9.6   9.6   9.6   7.2   7.2   7.2   7.2   7.2   7.2
   7.2   7.2   8.4   8.4   8.4   8.4   8.4   8.4   8.4   8.4   9.6   9.6 ]
 [19.2  19.2  19.2  19.2  19.2  19.2  14.4  14.4  14.4  14.4  14.4  14.4
  14.4  14.4  16.8  16.8  16.8  16.8  16.8  

In [228]:
CMTOT = np.multiply((CMF + CMQVTHORARIO), T) / 3600
print (CMTOT)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.

El coste total es el resultado de sumar el coste máquina y el de operario
CTOTHORARIO

In [229]:
CTOTHORARIO = CMOTHORARIO + CMTOT
print (CTOTHORARIO)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [1.